version: "3"
services:
  nginx:
    container_name: reverseproxy
    build: .
    ports:
      - "5020:80"
    links:
        - app1
        - app2
  app1:
    container_name: app1
    build: app1/
    restart: unless-stopped
  app2:
    container_name: app2
    build: app2/
